In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn as sk
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder



In [9]:
mentalhealth_df = pd.read_csv('mental_health_data final data.csv')
mentalhealth_df.drop(columns=['User_ID', 'Country',])
mentalhealth_df.head()

User_ID  Age             Gender   Occupation    Country  \
0        1   36               Male    Education  Australia   
1        2   48               Male  Engineering      Other   
2        3   18  Prefer not to say        Sales      India   
3        4   30         Non-binary  Engineering  Australia   
4        5   58               Male           IT        USA   

  Mental_Health_Condition Severity Consultation_History Stress_Level  \
0                     Yes      NaN                  Yes          Low   
1                      No      Low                   No          Low   
2                      No      NaN                  Yes       Medium   
3                      No   Medium                   No          Low   
4                     Yes      NaN                  Yes         High   

   Sleep_Hours  Work_Hours  Physical_Activity_Hours  Social_Media_Usage  \
0          7.6          46                        8                 2.2   
1          6.8          74                        2                 3.4   
2          7.1          77                        9                 5.9   
3          6.9          57                        4                 5.4   
4          4.7          45                       10                 3.3   

  Diet_Quality   Smoking_Habit Alcohol_Consumption Medication_Usage  
0      Healthy  Regular Smoker     Regular Drinker              Yes  
1    Unhealthy    Heavy Smoker      Social Drinker               No  
2      Healthy    Heavy Smoker      Social Drinker               No  
3      Average  Regular Smoker     Regular Drinker               No  
4    Unhealthy  Regular Smoker         Non-Drinker              Yes

In [14]:
feature = mentalhealth_df.drop(columns=['User_ID', 'Age', 'Gender', 'Occupation', 'Country', 'Mental_Health_Condition', 'Consultation_History', 'Sleep_Hours', 'Work_Hours', 'Physical_Activity_Hours', 'Social_Media_Usage', 'Medication_Usage'])


In [18]:
encoder = OrdinalEncoder()
encoded_data = encoder.fit_transform(feature)
print(encoded_data)

[[nan  1.  1.  3.  2.]
 [ 1.  1.  2.  0.  3.]
 [nan  2.  1.  0.  3.]
 ...
 [ 1.  2.  0.  1.  0.]
 [ 1.  0.  1.  2.  2.]
 [ 1.  0.  2.  1.  3.]]
